put:
  tags:
    - config
  summary: Quarantine clean up
  description: |
    Setting quarantine clean up time (clean up records older than). 
    > _**Note**_:The clean up range is defined in `hours`. 
  operationId: configQuarantine
  parameters:
    - $ref: ../components/parameters/apikey.yaml
  requestBody:
    $ref: ../components/requestBodies/adminCleanup.yaml
  responses:
    '200':
      $ref: ../components/responses/AdminCleanupResponse.yaml
    '403':
      $ref: ../components/responses/Error403.yaml
    '405':
      $ref: ../components/responses/Error405.yaml
    '500':
      $ref: ../components/responses/Error500.yaml
  security:
    - apikey: []
