language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: out/html
  on:
    branch: master
