language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  script: node scripts/gh-pages-deploy.js config/config.yaml
  on:
    branch: master
