source: '../openapi/openapi.yaml'
output: '../out'
redoc: 
  generate: true
  snippets: true
snippets:
  generate: true
  langs:
    - c_libcurl             # (default)
    - csharp_restsharp      #(default)
    #- go_native             #(default)
    - java_okhttp
    #- java_unirest          #(default)
    #- javascript_jquery
    #- javascript_xhr        #(default)
    - node_native           #(default)
    #- node_request
    #- node_unirest
    #- objc_nsurlsession     #(default)
    #- ocaml_cohttp          #(default)
    - powershell_webrequest
    - php_curl              #(default)
    #- php_http1
    #- php_http2
    - python_python3        #(default)
    #- python_requests
    #- vruby_native          #(default)
    - shell_curl            #(default)
    #- shell_httpie
    #- shell_wget
    #- swift_nsurlsession    #(default)

sdks:
  generate: false
  langs:
    - python
    - c
    - cpp-qt5-client
    - csharp
    - go 
    - java
    - javascript
    - jmeter
    - perl
    - php
    - powershell
    - ruby
    - scala-gatling      
pdf:
  generate: false
github:
  repo:
    update: false
  pages:
    update: false


        