source: '../openapi/openapi.yaml' ### provide the original file. 
output: '../out'                  ### output location               
snippets:
  generate: true                  ### feature toggle for: generating code samples. by default are generated in `out/code_samples`
  attachSnippets: true            ### feature toggle for: generating an openapi spec with attached code snippets. by default is generated in `out/openapi-with-snippets/metadefender-core-openapi3.docs.json`
  langs:                          ### list of the languages supported. enable/disable (uncomment/comment) which you want active or not. 
    - c_libcurl             # (default)
    - csharp_restsharp      #(default)
    #- go_native             #(default)
    - java_okhttp
    #- java_unirest          #(default)
    #- javascript_jquery
    #- javascript_xhr        #(default)
    - node_native           #(default)
    #- node_request
    #- node_unirest
    #- objc_nsurlsession     #(default)
    #- ocaml_cohttp          #(default)
    - powershell_webrequest
    - php_curl              #(default)
    #- php_http1
    #- php_http2
    - python_python3        #(default)
    #- python_requests
    #- vruby_native          #(default)
    - shell_curl            #(default)
    #- shell_httpie
    #- shell_wget
    #- swift_nsurlsession    #(default)
docs:
    generate: true              ### feature toggle for: generate the html documentation
    bundleSnippets: true        ### feature toggle for: add code snippets (samples) to the html docs. Requires for snippets.generate is enabled as well.
sdks:
  generate: true                ### feature toggle for: generate SDKs. default location would be `out/sdks`   
  updateInfo: true              ### feature toggle for: update the Info description block with the list of SDKs (links to Github location), Dependency on `github.sdks.update` and `github.pages.update`
  langs:                        ### list of the languages supported. enable/disable (uncomment/comment) which you want active or not. 
    - python
    - c
    - cpp-qt5-client
    - csharp
    - go 
    - java
    - javascript
    - jmeter
    - perl
    - php
    - powershell
    - ruby
    - scala-gatling      
    - python-flask
    - nodejs-express-server
    - java-inflector
    - jaxrs-cxf 
    - jaxrs-jersey
pdf:                            ### Not supported for now. 
  generate: false
github:
  sdks:                         
    update: true                ### feature toggle for: push the SDKs to github `repo/gh-pages/out/sdks`. Travis will do that as part of the deploy process. dependency on `sdks.generate`
  pages:
    update: true                ### feature toggle for: push the html docs to github `repo/gh-pages/out/sdks`. Travis will do that as part of the deploy process. dependency on `docs.generate`
