# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DLPResponseDlpInfoMetadataRemoval(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """DLPResponseDlpInfoMetadataRemoval - a model defined in OpenAPI

        :param result: The result of this DLPResponseDlpInfoMetadataRemoval.  # noqa: E501
        :type result: str
        """
        self.openapi_types = {
            'result': str
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'DLPResponseDlpInfoMetadataRemoval':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DLPResponse_dlp_info_metadata_removal of this DLPResponseDlpInfoMetadataRemoval.  # noqa: E501
        :rtype: DLPResponseDlpInfoMetadataRemoval
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self):
        """Gets the result of this DLPResponseDlpInfoMetadataRemoval.

        Result of the metadata removal process, possible values: * `removed` * `not removed` * `failed to remove`   # noqa: E501

        :return: The result of this DLPResponseDlpInfoMetadataRemoval.
        :rtype: str
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this DLPResponseDlpInfoMetadataRemoval.

        Result of the metadata removal process, possible values: * `removed` * `not removed` * `failed to remove`   # noqa: E501

        :param result: The result of this DLPResponseDlpInfoMetadataRemoval.
        :type result: str
        """
        allowed_values = ["removed", "not removed", "failed to remove"]  # noqa: E501
        if result not in allowed_values:
            raise ValueError(
                "Invalid value for `result` ({0}), must be one of {1}"
                .format(result, allowed_values)
            )

        self._result = result
