# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class YaraSourcesObjectLocalSources(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, source=None, state=None):  # noqa: E501
        """YaraSourcesObjectLocalSources - a model defined in OpenAPI

        :param source: The source of this YaraSourcesObjectLocalSources.  # noqa: E501
        :type source: str
        :param state: The state of this YaraSourcesObjectLocalSources.  # noqa: E501
        :type state: str
        """
        self.openapi_types = {
            'source': str,
            'state': str
        }

        self.attribute_map = {
            'source': 'source',
            'state': 'state'
        }

        self._source = source
        self._state = state

    @classmethod
    def from_dict(cls, dikt) -> 'YaraSourcesObjectLocalSources':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The YaraSourcesObject_local_sources of this YaraSourcesObjectLocalSources.  # noqa: E501
        :rtype: YaraSourcesObjectLocalSources
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source(self):
        """Gets the source of this YaraSourcesObjectLocalSources.

        The location (file path) of the files.  # noqa: E501

        :return: The source of this YaraSourcesObjectLocalSources.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this YaraSourcesObjectLocalSources.

        The location (file path) of the files.  # noqa: E501

        :param source: The source of this YaraSourcesObjectLocalSources.
        :type source: str
        """

        self._source = source

    @property
    def state(self):
        """Gets the state of this YaraSourcesObjectLocalSources.

        Defining if this source is being used or not  # noqa: E501

        :return: The state of this YaraSourcesObjectLocalSources.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this YaraSourcesObjectLocalSources.

        Defining if this source is being used or not  # noqa: E501

        :param state: The state of this YaraSourcesObjectLocalSources.
        :type state: str
        """
        allowed_values = ["disabled", "enabled"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state
